#
# BTstack example 'spp_counter' for ESP32 port
#
# Generated by /home/yuggo/esp/btstack-master/port/esp32
# On Thu Jul 27 22:13:22 2017

PROJECT_NAME := spp_counter
EXTRA_COMPONENT_DIRS := components

include $(IDF_PATH)/make/project.mk
